name: flutter_hmaps
description: A google maps with routes using FLutter
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^0.5.28+1
  dio: ^3.0.9
  cupertino_icons: ^0.1.3
  flutter_hooks: ^0.12.0
  flutter_dotenv: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env


